/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fangjia_itt_ITT */

#ifndef _Included_com_fangjia_itt_ITT
#define _Included_com_fangjia_itt_ITT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fangjia_itt_ITT
 * Method:    __itt_pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fangjia_itt_ITT__1_1itt_1pause
  (JNIEnv *, jclass);

/*
 * Class:     com_fangjia_itt_ITT
 * Method:    __itt_resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fangjia_itt_ITT__1_1itt_1resume
  (JNIEnv *, jclass);

/*
 * Class:     com_fangjia_itt_ITT
 * Method:    __itt_detach
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fangjia_itt_ITT__1_1itt_1detach
  (JNIEnv *, jclass);

/*
 * Class:     com_fangjia_itt_ITT
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fangjia_itt_ITT_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
